### PR TITLE
add a shell script to first pull in the paket packages and then run t…

### PR DESCRIPTION
**Pull request by railcar88**
…he fake build script

### CODE REVIEW

**Comment by andagr** [comment]
Apologies for the late reply!

Thanks for the pull request, I'll try to merge it in this weekend.

Did you test it with mono? Were there any issues?

**Comment by railcar88** [comment]
I only tested with Mono:) There were no issues at the time (Mono 3.12.1 and F# 3.1). I tried to build again and noticed the paket.lock and paket.dependencies were out of sync with regard to the RazorEngine upgrade. I issued a PR for that.

When I try to build now on Latest Mono and F# 4.0 I'm getting errors from the Data.fs file. I'll add an issue for those errors.

**Comment by andagr** [comment]
I'm having trouble merging this, github says:
"railcar88 wants to merge 2 commits into andagr:master from unknown repository"

**Comment by railcar88** [comment]
I'm sorry about that. I'll reissue another PR later tonight. Not thinking it would create issues, I deleted the fork that this PR came from. Now I know;)

**Pull request closed without merging**
